# Generated by Django 3.0.8 on 2020-07-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_examination'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExaminations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Examination')),
            ],
        ),
        migrations.AddField(
            model_name='studentsubjects',
            name='final_grade',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AddField(
            model_name='studentexaminations',
            name='studentSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentSubjects'),
        ),
        migrations.AddConstraint(
            model_name='studentexaminations',
            constraint=models.UniqueConstraint(fields=('studentSubject', 'examination'), name='unique_examinations'),
        ),
    ]
