# Generated by Django 3.0.8 on 2020-07-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
        ('student', '0002_auto_20200720_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubjects',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.Professor'),
        ),
    ]
