# Generated by Django 3.0.8 on 2020-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200720_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexaminations',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
