# Generated by Django 3.0.8 on 2020-07-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200720_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubjects',
            name='classroom',
            field=models.CharField(default='', max_length=6),
        ),
    ]
