# Generated by Django 3.0.8 on 2020-07-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_examination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='data',
            new_name='date',
        ),
    ]
