# Generated by Django 3.0.8 on 2020-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='type',
            field=models.CharField(choices=[('LB', 'laboratory examination'), ('MT', 'Mid-term examination'), ('PRE', 'presentation'), ('PR', 'Project report'), ('REP', 'report'), ('FE', 'final exam')], max_length=4),
        ),
    ]
