# Generated by Django 3.0.8 on 2020-07-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20200727_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='week',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], null=True),
        ),
    ]
