# Generated by Django 3.0.8 on 2020-08-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20200729_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='subjects.Classroom'),
        ),
    ]
