# Generated by Django 3.0.8 on 2020-08-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20200801_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classrooms',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
