# Generated by Django 3.0.8 on 2020-07-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0004_auto_20200720_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begins', models.TimeField()),
                ('ends', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('1', 'odd'), ('2', 'even')], max_length=1)),
                ('weekday', models.CharField(choices=[('1', 'monday'), ('2', 'tuesday'), ('3', 'wednesday'), ('4', 'thirsday'), ('5', 'friday'), ('6', 'saturday'), ('7', 'sunday')], max_length=1)),
                ('lecture_type', models.CharField(choices=[('1', 'laboratory'), ('2', 'theory class'), ('3', 'practical class')], max_length=1)),
                ('isCustom_time', models.BooleanField(default=False)),
                ('custom_begins', models.TimeField(null=True)),
                ('custom_ends', models.TimeField(null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Time')),
            ],
        ),
    ]
