# Generated by Django 3.0.8 on 2020-07-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='custom_begins',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='custom_ends',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Time'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week',
            field=models.CharField(choices=[('1', 'odd'), ('2', 'even'), ('3', 'both')], max_length=1),
        ),
    ]
