# Generated by Django 3.0.8 on 2020-07-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetable_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='week',
        ),
    ]
