# Generated by Django 3.0.8 on 2020-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_timetable_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('timetables', models.ManyToManyField(related_name='weeks', to='timetable.Timetable')),
            ],
        ),
        migrations.DeleteModel(
            name='timetable_week',
        ),
    ]
