# Generated by Django 3.0.8 on 2020-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200729_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='timetables',
            field=models.ManyToManyField(null=True, related_name='weeks', to='timetable.Timetable'),
        ),
    ]
