# Generated by Django 3.0.8 on 2020-07-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20200729_0152'),
        ('timetable', '0007_auto_20200729_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timetable',
            new_name='TimetableEntry',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='timetables',
            new_name='timetablesEntries',
        ),
    ]
