# Generated by Django 3.0.8 on 2020-07-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20200729_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='weekday',
            field=models.SmallIntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thirsday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')]),
        ),
    ]
