# Generated by Django 3.0.8 on 2020-08-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20200729_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.Time'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='weekday',
            field=models.SmallIntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')]),
        ),
    ]
