# Generated by Django 3.0.8 on 2020-08-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20200801_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='classrooms',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='timetable.Classroom'),
        ),
    ]
