# Generated by Django 3.1 on 2020-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20200801_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='timetable.Classroom'),
        ),
    ]
