# Generated by Django 3.0.8 on 2020-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'student'), (2, 'professor'), (3, 'staff'), (4, 'undefined')], default=4, max_length=1),
        ),
    ]
